language: cpp
compiler: gcc

# safelist
branches:
  only:
  - main

addons:
  sonarcloud:
    organization: "enesoztrk"
    token: $SONAR_TOKEN



script:
      - $TRAVIS_BUILD_DIR/scripts/cmake_and_sonarqube.sh
